2013/11/16 00:24:14 [error] [exception.CException] exception 'CException' with message 'RicardoController cannot find the requested view "index".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\RicardoController.php(9): CController->render('index')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): RicardoController->actionIndex()
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Ricardo')
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/Ricardo
---
2013/11/16 01:25:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp
---
2013/11/16 01:26:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp
---
2013/11/16 01:26:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp/index".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp/index')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp/index
---
2013/11/16 01:26:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp
---
2013/11/16 01:27:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp
---
2013/11/16 01:29:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp
---
2013/11/16 01:29:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "phpinfo".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('phpinfo')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/phpinfo
---
2013/11/16 01:29:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "lala".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('lala')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/lala
---
2013/11/16 01:30:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "phpinfo".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('phpinfo')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/phpinfo
---
2013/11/16 01:44:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infophp".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infophp')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infophp
---
2013/11/16 02:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "TestbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('TestbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/TestbbddController
---
2013/11/16 02:38:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "TestbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('TestbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/TestbbddController
---
2013/11/16 02:39:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "TestbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('TestbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/TestbbddController
---
2013/11/16 02:39:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "TestbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('TestbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/TestbbddController
---
2013/11/16 02:39:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "TestbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('TestbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/TestbbddController
---
2013/11/16 02:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbddController
---
2013/11/16 02:46:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'adminiMmTlHC'@'localhost' (using password: YES)' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\models\Usuarios.php(8): CModule->__get('db')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\TestbbddController.php(9): Usuarios->__construct()
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): TestbbddController->actionIndex()
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbdd')
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbdd
---
2013/11/16 02:46:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbddController
---
2013/11/16 02:46:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbddController
---
2013/11/16 02:46:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbddController
---
2013/11/16 02:46:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "testbbddController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbddControl...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbddController
---
2013/11/16 02:46:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'adminiMmTlHC'@'localhost' (using password: YES)' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\models\Usuarios.php(8): CModule->__get('db')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\TestbbddController.php(9): Usuarios->__construct()
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): TestbbddController->actionIndex()
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbdd')
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/testbbdd
---
2013/11/16 03:47:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'ODBC'@'localhost' (using password: NO)' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\models\Usuarios.php(8): CModule->__get('db')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\TestbbddController.php(9): Usuarios->__construct()
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): TestbbddController->actionIndex()
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('testbbdd')
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/testbbdd
---
2013/11/21 14:38:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infoPHPOpenshift".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infoPHPOpenshif...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infoPHPOpenshift
---
2013/11/21 14:38:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'andemail_usuario='ricardocb48@gmail.com'' at line 1. The SQL statement executed was: select * from notas where 1=1 andemail_usuario='ricardocb48@gmail.com' ;.
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\models\Notas_intervencion.php (30)
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\Notas_intervencionController.php (12)
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php (13)
2013/11/21 14:38:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'andemail_usuario='ricardocb48@gmail.com'' at line 1. The SQL statement executed was: select * from notas where 1=1 andemail_usuario='ricardocb48@gmail.com' ;' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\models\Notas_intervencion.php(30): CDbCommand->queryAll()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\Notas_intervencionController.php(12): Notas_intervencion->getNotas('ricardocb48@gma...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): Notas_intervencionController->actionIndex()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Notas_intervencion
---
2013/11/21 14:40:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "infoPHPOpenshift".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('infoPHPOpenshif...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/infoPHPOpenshift
---
2013/11/21 14:55:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Notas_intervencion".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('Notas_intervenc...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('Notas_intervenc...')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('site/Notas_inte...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/site/Notas_intervencion
---
2013/11/21 14:55:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "listar_notas".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('listar_notas')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('listar_notas')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Notas_intervencion/listar_notas
---
2013/11/21 14:55:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "listar_notas.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('listar_notas.ph...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('listar_notas.ph...')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Notas_intervencion/listar_notas.php
---
2013/11/21 14:56:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "listar_notas.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('listar_notas.ph...')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('listar_notas.ph...')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Notas_intervencion/listar_notas.php
---
2013/11/21 14:56:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Notas_intervencion/index.php
---
2013/11/21 14:56:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Notas_intervencion/index.php
---
2013/11/21 14:56:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Ricardo/index.p...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Ricardo/index.php
---
2013/11/21 14:57:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "otravista.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('otravista.php')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('otravista.php')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Ricardo/otravis...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Ricardo/otravista.php
---
2013/11/21 14:58:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Ricardo/index.p...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/Ricardo/index.php
---
2013/11/21 14:59:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "listar_notas".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('listar_notas')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('listar_notas')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Notas_intervenc...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php/Notas_intervencion/listar_notas
---
2013/11/22 12:49:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "listar_notas".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('listar_notas')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/listar_notas
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/Notas_intervencion
---
2013/11/22 12:49:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "listar_notas".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('listar_notas')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/listar_notas
---
2013/11/22 12:50:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "listar_notas".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('listar_notas')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/listar_notas
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/Notas_intervencion
---
2013/11/22 12:50:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "listar_notas".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('listar_notas')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/listar_notas
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/Notas_intervencion
---
2013/11/28 12:14:37 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.login" is not defined.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Usuarios), 'login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Usuarios), 'login', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\views\usuarios\login.php(20): CHtml::activeTextField(Object(Usuarios), 'login')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\UsuariosController.php(29): CController->render('login', Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): UsuariosController->actionLogin()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/login')
#16 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/usuarios/login
---
2013/11/28 12:14:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/login....')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/usuarios/login.php
---
2013/11/28 12:14:48 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.login" is not defined.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Usuarios), 'login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Usuarios), 'login', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\views\usuarios\login.php(20): CHtml::activeTextField(Object(Usuarios), 'login')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\UsuariosController.php(29): CController->render('login', Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): UsuariosController->actionLogin()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/login')
#16 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/usuarios/login
---
2013/11/28 12:15:01 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.login" is not defined.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Usuarios), 'login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Usuarios), 'login', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\views\usuarios\login.php(20): CHtml::activeTextField(Object(Usuarios), 'login')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\UsuariosController.php(29): CController->render('login', Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): UsuariosController->actionLogin()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/login')
#16 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/login
---
2013/11/28 12:16:00 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.login" is not defined.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Usuarios), 'login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Usuarios), 'login', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\views\usuarios\login.php(20): CHtml::activeTextField(Object(Usuarios), 'login')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\UsuariosController.php(29): CController->render('login', Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): UsuariosController->actionLogin()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/login')
#16 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/login
---
2013/11/28 12:16:02 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.login" is not defined.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Usuarios), 'login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Usuarios), 'login', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\views\usuarios\login.php(20): CHtml::activeTextField(Object(Usuarios), 'login')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\UsuariosController.php(29): CController->render('login', Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): UsuariosController->actionLogin()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/login')
#16 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/login
---
2013/11/28 12:16:19 [error] [exception.CException] exception 'CException' with message 'Property "Usuarios.login" is not defined.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Usuarios), 'login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Usuarios), 'login', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\views\usuarios\login.php(20): CHtml::activeTextField(Object(Usuarios), 'login')
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\UsuariosController.php(29): CController->render('login', Array)
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): UsuariosController->actionLogin()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/login')
#16 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/login
---
2013/11/28 12:33:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logeado".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('logeado')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('logeado')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/logead...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/logeado
---
2013/11/28 12:33:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/login
---
2013/11/28 12:34:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logeado".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('logeado')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('logeado')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/logead...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/logeado
---
2013/11/28 12:34:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/login
---
2013/11/28 12:34:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logeado".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('logeado')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('logeado')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/logead...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/logeado
---
2013/11/28 12:35:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login
---
2013/11/28 12:35:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logeado".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('logeado')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('logeado')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/logead...')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/Usuarios/logeado
---
2013/11/28 12:43:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/cerrar".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/cerrar')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/cerrar
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/usuarios/logueado
---
2013/12/03 13:58:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "LoginController".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 13:59:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/cerrar".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/cerrar')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/cerrar
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:05:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/cerrar".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/cerrar')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/cerrar
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:47:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
---
2013/12/03 14:47:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 14:48:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 14:48:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 14:48:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/
---
2013/12/03 14:48:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/
---
2013/12/03 14:48:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/
---
2013/12/03 14:48:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 14:48:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:49:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:49:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "initiate".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
---
2013/12/03 14:50:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:50:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:50:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
---
2013/12/03 14:50:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/cerrar".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/cerrar')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/cerrar
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:51:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "int".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('int')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/int
---
2013/12/03 14:51:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:52:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:52:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:52:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('init')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/init
---
2013/12/03 14:52:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 14:52:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/cerrar".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/cerrar')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/cerrar
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:53:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/cerrar".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('test/cerrar')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/test/cerrar
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:54:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login/login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login/login
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:55:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login/login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login/login
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login/logueado
---
2013/12/03 14:55:32 [error] [exception.CException] exception 'CException' with message 'LoginController cannot find the requested view "index".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php(37): CController->render('index', Array)
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): LoginController->actionIndex()
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login
---
2013/12/03 14:56:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 14:56:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/
---
2013/12/03 14:57:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "init".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/index.php
---
2013/12/03 15:02:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login/login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login/login
---
2013/12/03 15:02:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login/login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login/login
---
2013/12/03 15:02:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(270): CController->missingAction('login')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('login')
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login/login')
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login/login
---
2013/12/03 15:32:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "protocolos".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('protocolos')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/protocolos
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/menu
---
2013/12/03 15:32:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "farmacos".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('farmacos')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/farmacos
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/menu
---
2013/12/03 15:41:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "usuarios".' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/usuarios
---
2013/12/03 15:46:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rescueincloud.loginform' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `LoginForm`.
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php (19)
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php (13)
2013/12/03 15:46:42 [error] [exception.CDbException] exception 'CDbException' with message 'The table "LoginForm" for active record class "LoginForm" cannot be found in the database.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(LoginForm))
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(711): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(156): CActiveRecord->setAttribute('attributes', NULL)
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php(19): CActiveRecord->__set('attributes', NULL)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): LoginController->actionIndex()
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login
---
2013/12/03 15:47:00 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rescueincloud.loginform' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `LoginForm`.
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php (19)
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php (13)
2013/12/03 15:47:00 [error] [exception.CDbException] exception 'CDbException' with message 'The table "LoginForm" for active record class "LoginForm" cannot be found in the database.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(LoginForm))
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(711): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(156): CActiveRecord->setAttribute('attributes', Array)
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php(19): CActiveRecord->__set('attributes', Array)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): LoginController->actionIndex()
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login
---
2013/12/03 15:47:49 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rescueincloud.loginform' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `LoginForm`.
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php (19)
in C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php (13)
2013/12/03 15:47:49 [error] [exception.CDbException] exception 'CDbException' with message 'The table "LoginForm" for active record class "LoginForm" cannot be found in the database.' in C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(LoginForm))
#1 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(711): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\db\ar\CActiveRecord.php(156): CActiveRecord->setAttribute('attributes', NULL)
#3 C:\xampp\htdocs\rescueincloud\php\rescueincloud\protected\controllers\LoginController.php(19): CActiveRecord->__set('attributes', NULL)
#4 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\actions\CInlineAction.php(49): LoginController->actionIndex()
#5 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#10 C:\xampp\htdocs\rescueincloud\php\rescueincloud\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\rescueincloud\php\rescueincloud\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/rescueincloud/php/rescueincloud/login
HTTP_REFERER=http://localhost/rescueincloud/php/rescueincloud/login
---
